# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js Build and Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  WEBUI_NO_SUFFIX: 1

jobs:
  build-dist:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build
    # - run: npm test
    - uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ${{github.workspace}}/dist/*

  build-electron:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x
        cache: 'npm'
    - run: pip3 install setuptools || pip3 install --break-system-packages setuptools
    - run: npm ci --prefer-offline --no-audit --maxsockets 1 --noproxy registry.npmjs.org
    - run: npm run ebuild
    - uses: actions/upload-artifact@v4
      with:
        name: electron
        path: ${{github.workspace}}/release/*.*

  release:
    runs-on: ubuntu-latest
    needs: [build-dist, build-electron]
    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
    - uses: actions/download-artifact@v4
      with:
        name: electron
        path: release/
    - name: Create dist tar.gz archive
      run: tar zcvf webcface-webui_$(echo ${{github.ref}} | sed 's#refs/tags/v##').tar.gz dist
    - name: Prepare deb package files
      run: |
        mkdir -p .debpkg/usr/share/webcface/
        cp -r dist .debpkg/usr/share/webcface/
    - name: Create dist deb package
      uses: jiro4989/build-deb-action@v3
      with:
        package: webcface-webui
        package_root: .debpkg
        maintainer: "na-trium-144 <na-trium-144@users.noreply.github.com>"
        version: ${{ github.ref }} # refs/tags/v*.*.*
        arch: 'all'
        desc: 'UI Application for WebCFace'
    - name: Release
      uses: docker://antonyurchenko/git-release:v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ALLOW_EMPTY_CHANGELOG: true
      with:
        args: "webcface-webui_*.tar.gz,webcface-webui_*.deb,release/webcface-desktop_*.zip,release/webcface-desktop_*.tar.gz,release/webcface-desktop_*.deb"
